### ISSUE TITLE
Create more performant displayPrice function

### ISSUE THREAD

**Issue by matchello** [TotomInc/blackmarket-reloaded#14]
Please see this [commit](https://github.com/matchello/blackmarket-reloaded/commit/6769e837ba132d857c36718b437b200b35594cb1)

The function is now much more performant. Will be significant on later progress.

**Comment by TotomInc** [comment]
Nice one, is there a way to get a pull request of only this change and not have all the others commits you have done (like when you added the production).

Thanks!

**Comment by matchello** [comment]
Sorry GitHub still makes me crazy ;)

Here the PullRequest:
#15

**Comment by TotomInc** [comment]
Yeah, I saw all your reverted commits, don't worry I'm also pretty new with the pull requests, branches and forks.

**Comment by TotomInc** [comment]
Merged, thanks.
