### ISSUE TITLE
Hard reset not working.

### ISSUE THREAD

**Issue by TotomInc** [TotomInc/blackmarket-reloaded#35]
It seems that hard reset is not working anymore. I just tried hard-reset on the official game lin (totominc.github.io/blackmarket-reloaded).

When clicking the 'yes' button of hard-reset, nothing act.

**Comment by matchello** [comment]
Please try:
- save game
- reload
- options -> hard reset

I think, there will be an js error, because I added some vars to save.

We have to write an adapter, which checks if the save vars exists or not (if not, default value has to be set).

I'll do this next.

**Comment by TotomInc** [comment]
Oh yeah I haven't though if that. Let me do the save check function when I'm .
