### ISSUE TITLE
Failed loading save game

### ISSUE THREAD

**Issue by matchello** [TotomInc/blackmarket-reloaded#6]
Hi,

today after one day closed game, I've got following error:

`TypeError: this.actions.list[t] is undefined
Stack-Trace:
research.display@http://totominc.github.io/blackmarket-reloaded/app/game-optimized/research-center.js:1:2150
[..]

**Comment by TotomInc** [comment]
Hello,

I worked on small improvements all the weekend, I touched a bit on some core.js, maybe it can be the cause of that. I will take a look at your bug.

Thanks for reporting this.

**Comment by matchello** [comment]
#7 
Have a fix now.

**Comment by TotomInc** [comment]
#8

Bug seems to be fixed.
